/**
 * ==========================================================
 * pdf.js
 * Generates PDF Report using jsPDF
 * ==========================================================
 */

function downloadReport() {

    const { jsPDF } = window.jspdf;

    const doc = new jsPDF();

    const state = getState();

    const totals = computeTotals(state);

    let y = 20;

    /* -----------------------------------------
       Title
    ----------------------------------------- */

    doc.setFontSize(22);
    doc.text("Cash-Flow Report", 20, y);

    y += 12;

    doc.setFontSize(11);

    doc.text(
        `Generated : ${new Date().toLocaleString()}`,
        20,
        y
    );

    y += 12;

    /* -----------------------------------------
       Summary
    ----------------------------------------- */

    doc.setFontSize(15);

    doc.text("Financial Summary",20,y);

    y += 10;

    doc.setFontSize(12);

    doc.text(
        `Salary : ${UI.formatMoney(state.salary)}`,
        20,
        y
    );

    y += 8;

    doc.text(
        `Total Expenses : ${UI.formatMoney(totals.totalExpenses)}`,
        20,
        y
    );

    y += 8;

    doc.text(
        `Remaining Balance : ${UI.formatMoney(totals.balance)}`,
        20,
        y
    );

    y += 8;

    doc.text(
        `Currency : ${state.currency}`,
        20,
        y
    );

    y += 15;

    /* -----------------------------------------
       Expense List
    ----------------------------------------- */

    doc.setFontSize(15);

    doc.text("Expense List",20,y);

    y += 10;

    if(state.expenses.length===0){

        doc.setFontSize(12);

        doc.text("No expenses added.",20,y);

    }

    else{

        doc.setFontSize(12);

        state.expenses.forEach((expense,index)=>{

            if(y>270){

                doc.addPage();

                y=20;

            }

            doc.text(

                `${index+1}. ${expense.name}`,

                20,

                y

            );

            doc.text(

                UI.formatMoney(expense.amount),

                150,

                y,

                {align:"right"}

            );

            y+=8;

        });

    }

    y+=10;

    /* -----------------------------------------
       Footer
    ----------------------------------------- */

    doc.setFontSize(11);

    doc.text(

        `Total Expenses : ${state.expenses.length}`,

        20,

        y

    );

    y+=8;

    doc.text(

        "Generated by Cash-Flow Salary & Expense Tracker",

        20,

        y

    );

    doc.save("CashFlow_Report.pdf");

}

/* -----------------------------------------
   Global
----------------------------------------- */

window.PDFManager={

    downloadReport

};